#define WIN32_LEAN_AND_MEAN
#define _WINSOCKAPI_
// AeonBrowser — I2pdShim.cpp
// DelgadoLogic | Senior Security Engineer
//
// PURPOSE: Launches and manages i2pd (the C++ I2P router) as a child process
// providing an HTTP proxy at 127.0.0.1:4444 and SOCKS5 at 127.0.0.1:4447.
// .i2p domains and i2p:// URLs are routed through this proxy.
//
// DESIGN: We run i2pd.exe as a background child process rather than linking
// i2pd as a library (unlike Tor where we use Arti natively). Reason:
//   1. i2pd is GPL-licensed — linking statically would require GPL disclosure.
//      Running as a separate process is the safe legal boundary.
//   2. i2pd is a heavy dependency (~15MB). Child process = easy to ship/update.
//
// SHIPPED BINARY: i2pd.exe is placed in {app}\Network\i2pd.exe during install.
// Config: {APPDATA}\DelgadoLogic\Aeon\i2pd\i2pd.conf
//
// IT TROUBLESHOOTING:
//   - I2P takes 2-10 minutes to integrate (join DHT, find tunnels).
//     "Loading..." status is normal for the first few minutes.
//   - i2pd.exe not found: Check {app}\Network\ dir after install.
//   - Port 4444 blocked by firewall: Add outbound UDP rule for i2pd.exe.
//   - .i2p site not loading: Tunnel may be rebuilding. Retry in 30-60 seconds.
//   - Privacy note: I2P integrates with the global I2P network. Your node
//     participates in routing OTHER USERS' traffic by default (unlike Tor
//     exit nodes which are opt-in). Aeon disables transit tunnels by default
//     (set {transit.enabled = false} in i2pd.conf).

#include "I2pdShim.h"
#include <windows.h>
#include <shlobj.h>
#include <cstdio>

namespace I2pdShim {

static HANDLE g_hProcess = nullptr;
static HANDLE g_hThread  = nullptr;

static void WriteDefaultConfig(const char* confPath) {
    FILE* f = nullptr;
    fopen_s(&f, confPath, "w");
    if (!f) return;

    fprintf(f,
        "# Aeon Browser — i2pd configuration\n"
        "# Auto-generated by Aeon Browser v1.0\n"
        "# DelgadoLogic.tech\n\n"
        "[http]\n"
        "enabled   = true\n"
        "address   = 127.0.0.1\n"
        "port      = 4444\n\n"
        "[httpproxy]\n"
        "enabled   = true\n"
        "address   = 127.0.0.1\n"
        "port      = 4444\n\n"
        "[socksproxy]\n"
        "enabled   = true\n"
        "address   = 127.0.0.1\n"
        "port      = 4447\n\n"
        "[websockets]\n"
        "enabled   = false\n\n"
        "[upnp]\n"
        "enabled   = false\n\n"
        "[transit]\n"
        "# AEON PRIVACY: transit tunnels disabled.\n"
        "# Enabling routes OTHER users' traffic through your machine.\n"
        "# Set to true ONLY if you want to contribute bandwidth to I2P.\n"
        "enabled   = false\n"
        "maxTransitTunnels = 0\n\n"
        "[log]\n"
        "level     = warn\n"
        "dest      = file\n"
    );
    fclose(f);
    fprintf(stdout, "[I2pd] Default config written: %s\n", confPath);
}

bool Start(const char* app_install_dir) {
    if (g_hProcess) {
        fprintf(stdout, "[I2pd] Already running.\n");
        return true;
    }

    // Build paths
    char exePath[MAX_PATH], confDir[MAX_PATH], confPath[MAX_PATH];
    _snprintf_s(exePath,  sizeof(exePath),  _TRUNCATE,
        "%s\\Network\\i2pd.exe", app_install_dir);

    char appData[MAX_PATH];
    SHGetFolderPathA(nullptr, CSIDL_APPDATA, nullptr, 0, appData);
    _snprintf_s(confDir,  sizeof(confDir),  _TRUNCATE,
        "%s\\DelgadoLogic\\Aeon\\i2pd", appData);
    _snprintf_s(confPath, sizeof(confPath), _TRUNCATE,
        "%s\\i2pd.conf", confDir);

    CreateDirectoryA(confDir, nullptr);

    // Write default config if not present
    if (GetFileAttributesA(confPath) == INVALID_FILE_ATTRIBUTES)
        WriteDefaultConfig(confPath);

    // Check i2pd.exe exists
    if (GetFileAttributesA(exePath) == INVALID_FILE_ATTRIBUTES) {
        fprintf(stderr, "[I2pd] i2pd.exe not found: %s\n"
            "       Install Aeon Browser fully (Network component).\n", exePath);
        return false;
    }

    // Launch i2pd.exe with our config
    char cmdLine[MAX_PATH * 2];
    _snprintf_s(cmdLine, sizeof(cmdLine), _TRUNCATE,
        "\"%s\" --conf=\"%s\" --datadir=\"%s\"", exePath, confPath, confDir);

    STARTUPINFOA si = {};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESHOWWINDOW;
    si.wShowWindow = SW_HIDE; // Hidden — background process

    PROCESS_INFORMATION pi = {};
    if (!CreateProcessA(nullptr, cmdLine, nullptr, nullptr, FALSE,
            CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi)) {
        fprintf(stderr, "[I2pd] CreateProcess failed: %lu\n", GetLastError());
        return false;
    }

    g_hProcess = pi.hProcess;
    g_hThread  = pi.hThread;
    fprintf(stdout, "[I2pd] i2pd started (PID %lu). "
        "HTTP proxy: 127.0.0.1:4444 | SOCKS5: 127.0.0.1:4447\n"
        "        I2P integration takes 2-10 minutes.\n", pi.dwProcessId);
    return true;
}

void Stop() {
    if (!g_hProcess) return;
    TerminateProcess(g_hProcess, 0);
    WaitForSingleObject(g_hProcess, 3000);
    CloseHandle(g_hProcess);
    CloseHandle(g_hThread);
    g_hProcess = nullptr;
    g_hThread  = nullptr;
    fprintf(stdout, "[I2pd] i2pd stopped.\n");
}

bool IsRunning() {
    if (!g_hProcess) return false;
    DWORD code;
    GetExitCodeProcess(g_hProcess, &code);
    return (code == STILL_ACTIVE);
}

} // namespace I2pdShim
